services:
  sharedock:
    container_name: sharedock
    image: sharedock:local
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TRUST_PROXY=false
    volumes:
      - "./data:/opt/app/backend/data:rw,z"
      - "./data/images:/opt/app/frontend/public/img:rw,z"
  #      - "./config.yaml:/opt/app/config.yaml"

  # To add ClamAV scanning, see docs/docs/setup/integrations.md.
